name: Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan

    - name: Generate
      run: cmake . -B.build

    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest . --verbose

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan
        export PATH=$PATH:/home/runner/.local/bin
        sudo ln -s ~/.local/bin/conan /usr/local/bin/conan

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest . --verbose

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest . --verbose
